#!/bin/bash

## Instructions counter.
## Year: 2020
## Author: Manel Lurbe Sempere <malursem@gap.upv.es>

echo ''
echo 'Instructions_counter Copyright (C) 2020 Manel Lurbe Sempere <malursem@gap.upv.es>.'
echo ''

rm -rf ../libpfm-4.10.1/perf_examples/Instructions_counter*

if cp Makefile Instructions_counter.c ../libpfm-4.10.1/perf_examples/ ; then
	if cd ../libpfm-4.10.1/perf_examples/ ; then
		if make ; then
			if cp -rf Instructions_counter ../../ ; then
				echo "Process finished successfully."
			else
				echo "Error copying programs."
			fi
		else
			echo "Error compiling the program."
		fi
	else
		echo "Error changing the directory."
	fi
else
	echo "Error coping files."
fi